[versions]
agp = "9.3.2"
kotlin = "2.4.10"
coreKtx = "1.19.0"
libxposed = "102.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

